build:
  environment:
    variables:
      JWT_SECRET: "ajr490lsmfjskr05fskfwcösdisjflw93mahr95odöasjjd2os75j3öa0euhjak"
  nodes:
    coverage:
      tests:
        override:
          - command: npm run pretest && npm run test
            coverage:
              file: coverage/clover.xml
              format: clover